# Site settings
title: "엄두용 | 지속적인 열정을 가진 개발자"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "지속적인 열정을 가진 개발자"
resume_title:                   "About Me"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "endyd1567@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "555-7334"
resume_contact_address:         "742 Evergreen Terrace, Springfield"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • lisasimpson@youremailaddress.com"
display_header_contact_info:    "false"

resume_header_intro: 
"<p>안녕하세요. 열정이 식지 않기 위해 노력하는 개발자 엄두용입니다.</p><p>매일 아침 다이어리에 목표를 작성하며 '오늘에 최선을 다하자' 는 생각을 갖고 하루를 시작합니다.</p><p>문제점을 발견하면 더 나은 방향으로 갈 수 있도록 사람들과 고민하는 것을 좋아합니다.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
#resume_section_recognition:     true
#resume_section_links:           true
#resume_section_associations:    true
#resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/endyd1567"
  resume_website_url:           "https://endyd1567.tistory.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default


